version: '3.5'
services:
  postgres:
    image: postgres:16.0
    container_name: web3_db
    environment:
      POSTGRES_USER: web3_user
      POSTGRES_PASSWORD: alina0811
    ports:
      - "5432:5432"
    volumes:
      - wildfly_data:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb
    networks:
      - default
volumes:
  wildfly_data:
networks:
  default:
    driver: bridge